version: "3.8"

services:
  recipes-db:
    image: postgres:latest
    container_name: recipes-DB
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Recipes AI DB 
  recipesAI-db:
    image: postgres:latest
    container_name: recipes-ai-DB
    ports:
      - "5433:5432"
    env_file:
      - aidb.env
    volumes:
      - ./ai-init.sql:/docker-entrypoint-initdb.d/ai-init.sql
